title: "DirtyTesterやまずんのワイワイワールド"
summary: "やまずんに関係する情報をまとめる本です。イラスト：タスマニア・デビ男"
topics: [introduction]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 01_what_is_yamazun
  - 02_passion_behind_dirty_tester
  - 03_passion_behind_bakibaki_qa
  - 04_positioning_paper_of_qa
  - 05_i_am_not_full_stack_qa
  - 06_perfectqa_perfectstyle
  - 07_perspectives_and_reason
  - 08_what_is_qa_engineer_mindset
  - 09_mvv
  - 10_philosopher
  - 11_profile_as_coach
  - 13_yamazun_community_manifesto
  - 14_passion_behind_system_fixcer